services:
  - type: web
    name: english-hindi-translator
    env: python
    buildCommand: pip install -r website/requirements.txt
    startCommand: cd website && python app.py
    envVars:
      - key: PORT
        value: 10000
